name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} docker.io
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/blackjackgo:${GITHUB_SHA::7} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/blackjackgo:${GITHUB_SHA::7}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop blackjackgo || true # Останавливаем, если уже запущен
            docker rm blackjackgo || true   # Удаляем контейнер, если есть
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/blackjackgo:${GITHUB_SHA::7}
            docker run -d --name blackjackgo ${{ secrets.DOCKERHUB_USERNAME }}/blackjackgo:${GITHUB_SHA::7}
    ```

